### ISSUE TITLE
Error when used with AppVeyor

### ISSUE THREAD

**Issue by Tieske** [moteus/luacov-coveralls#14]
I'm trying to set up Penlight to collect the WIndows coverage statistics, but I'm running into an error

This is the configuration:
```yaml
shallow_clone: true

environment:
  matrix:
  - LUA: "lua 5.1"
  - LUA: "lua 5.2"
  - LUA: "lua 5.3"
  - LUA: "luajit 2.0"
  - LUA: "luajit 2.0 --compat 5.2"
  - LUA: "luajit 2.1"
  - LUA: "luajit 2.1 --compat 5.2"

before_build:
  - set PATH=C:\Python27\Scripts;%PATH%
  - pip install hererocks
  - hererocks here --%LUA% -rlatest
  - call here\bin\activate
  - luarocks install luacov-coveralls

build_script:
  - luarocks make

test_script:
  - lua run.lua tests --luacov

on_success:
  - luacov-coveralls
```

and this is the error I'm getting:
```
Running tests\test-types.lua
Running tests\test-tzone.lua
Running tests\test-url.lua
Running tests\test-utils.lua
Running tests\test-vector.lua
Running tests\test-xml.lua
Run completed successfully
luacov-coveralls
C:\projects\penlight\here\bin\lua.exe: ...ht\here\/share/lua/5.1/luacov\coveralls\repo\git.lua:57: attempt to call field 'fullpath' (a nil value)
stack traceback:
	...ht\here\/share/lua/5.1/luacov\coveralls\repo\git.lua:57: in function 'new'
	...ight\here\/share/lua/5.1/luacov\coveralls\CiRepo.lua:7: in function 'try_any_repo'
	...ight\here\/share/lua/5.1/luacov\coveralls\CiRepo.lua:22: in function 'new'
	...ht\here\/share/lua/5.1/luacov\reporter\coveralls.lua:66: in function 'new'
	...cts\penlight\here\/share/lua/5.1/luacov\reporter.lua:388: in function <...cts\penlight\here\/share/lua/5.1/luacov\reporter.lua:383>
	(tail call): ?
	...\rocks\luacov-coveralls\0.2.2-1\bin\luacov-coveralls:160: in main chunk
	[C]: ?
Command exited with code 1
```

Any ideas how to fix this?

EDIT: the PR showing the behaviour https://github.com/stevedonovan/Penlight/pull/281
