### ISSUE TITLE
Tweak Github Actions support to match official app

### ISSUE THREAD

**Issue by alerque** [moteus/luacov-coveralls#21]
The official [Coveralals app](https://github.com/coverallsapp/github-action) for Github Actions (not useful for Lua, but great otherwise) uses an internal parameter `github-token` as the identifier instead of having to pass a custom secret token.

See related [upstream issue here](https://github.com/lemurheavy/coveralls-public/issues/1353).

We should update the support here to do the same thing.

* [x] Use `github` as the action name
* [x] Drop the custom token handling and pass `github-token`

**Comment by alerque** [comment]
(If you can feel free to assign this issue to me so I don't forget about it.)

**Comment by moteus** [comment]
Do I meiss some think but `github-token` pass just as regular [repo_token](https://github.com/coverallsapp/github-action/blob/8d2940685b011d380ca033e2786e92812f915b1d/src/run.ts#L22) and service name is just [github](https://github.com/coverallsapp/github-action/blob/8d2940685b011d380ca033e2786e92812f915b1d/src/run.ts#L24)
Token if i understend correctly have to be passed via command line, service name can be also passed via command line arguments. 
Do you whant to calculate these parameters?

**Comment by LPGhatguy** [comment]
My team recently switched from Travis-CI to GitHub Actions and ran into this discrepancy! You _need_ to pass `github` as the service name or luacov-coveralls won't be able to handle the GitHub token when passed as the repo token.

We run this right now:

```yaml
- name: Report to Coveralls
  run: luacov-coveralls --repo-token $REPO_TOKEN --service-name github
  env:
    REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

But it would be nice to instead be able to just write:

````yaml
- name: Report to Coveralls
  run: luacov-coveralls --repo-token $REPO_TOKEN
  env:
    REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

I think the fix ends up being very simple. Instead of using `actions` as the service name when GitHub Actions is detected, use `github` instead?

**Comment by alerque** [comment]
@LPGhatguy I just submitted a PR (#23) to fix the service name, and also I think if the env variable is set right in the first pace you can skip the repo token arg too:

```yaml
- name: Report to Coveralls
  run: luacov-coveralls
  env:
    COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Would you be able to test this by chance?

**Comment by LPGhatguy** [comment]
I took a stab at this in the PR that GitHub marked as related to this issue. It looks like the configuration I tried didn't work out. I can look into this more detail if that isn't enough information!

**EDIT**: I don't think I installed the version of luacov-coveralls from your branch correctly, oops. LuaRocks is a little funky to try to navigate.

**Comment by alerque** [comment]
@LPGhatguy Thanks for the help testing this in a real world scenario! That means a lot.

I think what's happening is that even though you check out the right source, the rockspec you then use goes back and fetches the old released source. I'll look and see if I can find a way to do it from the local tree.

**Comment by alerque** [comment]
@moteus I have confirmed via [this test run](https://github.com/sile-typesetter/cassowary.lua/pull/17/checks?check_run_id=392915021#step:7:9) that these proposed changes do work as expected, I think this can be merged now.

**Comment by moteus** [comment]
In your job you got `Upload error: Couldn't find a repository matching this job.` is it expected? also to be sure that uses correct version of the luaco-coveralls it is possible to add `-v` flag.

**Comment by alerque** [comment]
@moteus I think what you are seeing is a false alarm. Github is not showing test results for the commit I actually wanted to show off. I had pushed a temporary commit with the special rockspec to get this branch (and also ran with -v), and it all worked fine. Then I forced push that commit off and went back to a cleaned up version in anticipation of this fix being released. The result is the error you see now. I poked around and can't even find the logs for the now non-existent commit. My link above does not go to what I actually linked at the time.

**Comment by Ismoh** [comment]
> @LPGhatguy I just submitted a PR (#23) to fix the service name, and also I think if the env variable is set right in the first pace you can skip the repo token arg too:
> 
> ```yaml
> - name: Report to Coveralls
>   run: luacov-coveralls
>   env:
>     COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
> ```
> 
> Would you be able to test this by chance?

I was struggling for days to get this running.
The important change is to use the github token instead the coveralls token.
This isnt mentioned anywhere in the docs or in the lua-example repo.

Can anyone add this for the ppl, who might struggle with this in future?

```
- name: Generate coverage report with luacov-coveralls
      env:
        #github-token: ${{ secrets.github_token }}
        #COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COVERALLS_DEBUG: true
      run: |
        ${{ github.workspace }}/luajit/bin/luacov-coveralls -v
```
